name: Java test with maven

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repos
      uses: actions/checkout@v3
      with: 
        repository: 'nitin-2137150/project-python-june-24-niting' 
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Build and test
      run: | 
        echo "mvn clean verify sonar:sonar -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}"

    - name: Generate JUnit test report
      run: | 
        echo "mvn junit report"

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports/

    - name: Display test results
      run: cat target/surefire-reports/*.xml

    - name: Upload sonarqube code coverage report
      uses: codecov/codecov-action@v3
      with:
        files: build/report/jacoco/test/TestCoverage.xml
        token: $ {{ secrets.CODECOV_TOKEN }}

    - name: Display code coverage summary
      run: |
        echo "Code coverage: $COVERAGE"

    
