name: SonarQube Analysis

on:
  pull_request:
    branches:
      - develop

jobs:
  sonarQube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Cache SonarQube CLI
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        echo "Run SonarQube Analysis"

    - name: Post SonarQube Report
      run: |
        echo "SonarQube Analysis Report"
        PR_NUMBER=$(echo $GITHUB_REF | awk -F '/' '{print $3}')
        SONAR_PROJECT_KEY=your_project_key
        SONAR_SERVER=https://your-sonarqube-server.com
        SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}

        # Get SonarQube report URL
        SONAR_REPORT_URL=$(curl -s -u $SONAR_TOKEN: $SONAR_SERVER/api/project_analyses/search?project=$SONAR_PROJECT_KEY | jq -r '.analyses[0].url')

        # Post comment on the pull request
        COMMENT="SonarQube analysis report: $SONAR_REPORT_URL"
        gh pr comment $PR_NUMBER --body "$COMMENT"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
